config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "weather#index"

  get 'forecast', to: 'weather#show'
  get 'missing_credentials', to: 'weather#missing_credentials'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/place.rb
# frozen_string_literal: true

class Place
  include ActiveModel::API

  attr_accessor :lat, :lng, :cached, :address

  alias_method :latitude, :lat
  alias_method :longitude, :lng

  validates :lat, :lng, presence: true

  def coords
    "#{lat},#{lng}"
  end
  alias_method :coordinates, :coords
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  helper_method :place, :forecast, :cached?

  before_action :ensure_credentials_exist_for_env!, except: :missing_credentials

  def index; end

  def show
    if params[:address].blank?
      redirect_to root_path, flash: { error: 'Please enter a valid address' }
    elsif place.blank?
      redirect_to root_path, flash: { warning: 'Address could not be resolved' }
    end
  end

  def missing_credentials
    redirect_to root_path if GeocodingService.api_key.present? && WeatherService.api_key.present?
  end

  private

  def place
    @place ||= GeocodingService.new(params[:address]).place
  end

  def weather_service
    @weather_service ||= WeatherService.new(place)
  end

  def cached?
    weather_service.cached?
  end

  def forecast
    @forecast ||= weather_service.parsed_response
  end

  def ensure_credentials_exist_for_env!
    return if GeocodingService.api_key.present? && WeatherService.api_key.present?

    redirect_to(missing_credentials_path) and return
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/weather_helper.rb
module WeatherHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title= content_for(:title) || 'Ben Weather'
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
    %meta{:content => "yes", :name => "mobile-web-app-capable"}/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    %link{:href => "/icon.png", :rel => "icon", :type => "image/png"}/
    %link{:href => "/icon.svg", :rel => "icon", :type => "image/svg+xml"}/
    %link{:href => "/icon.png", :rel => "apple-touch-icon"}/
    = stylesheet_link_tag :app, "data-turbo-track": "reload"
    =# javascript_importmap_tags
  %body
    = link_to root_path, id: 'rootLink' do
      %h1#logo Ben Weather
    - if flash.present?
      #flash
        - flash.each do |type, message|
          %div{ class: type }= message
    = yield

app/views/weather/_panel.html.haml
- small ||= false
- skycon_size ||= small == true ? 32 : 128
- icon_underscore = forecast['icon']&.underscore
- any_precip ||= false
- force_display_precip_header = small && any_precip

.weather_panel
  - if small
    - time = Time.at(forecast['time'])
    .forecastTime= Time.now.hour == time.hour ? 'Now' : time.strftime("%l %P")
  %canvas.skycon{ width: skycon_size, height: skycon_size, title: icon_underscore&.humanize, data: { icon: icon_underscore } }
  - if forecast['precipProbability'].to_f.positive?
    - percent_rounded = (forecast['precipProbability'].to_f * 100).to_i
    %h4.precipProbability{ title: 'Precipitation Probability' }
      = number_to_percentage(percent_rounded, precision: 0)
  - elsif force_display_precip_header
    %h4 &nbsp;
  %h4.temp
    = forecast['temperature'].to_f.round
    &deg;

app/views/weather/index.html.haml
= form_tag forecast_path, method: 'get', remote: false do
  = text_field_tag :address, nil, placeholder: 'Search Address or Zip Code', size: 50

  = submit_tag 'Fetch'

app/views/weather/missing_credentials.html.haml
%h1 Missing Credentials

.message
  You are missing API key credentials for critical services required to run the application
  In order to set them, run <i>bundle exec rails credentials:edit</i> from the root directory and add them.

.missing_credentials
  - if GeocodingService.api_key.blank?
    .error
      Missing
      = link_to 'Google Maps API Key', 'https://developers.google.com/maps', target: '_blank'
  - if WeatherService.api_key.blank?
    .error
      Missing
      = link_to 'Pirate Weather API Key', 'https://pirate-weather.apiable.io/', target: '_blank'

app/views/weather/show.html.haml
Weather for:
= place.address

- if cached?
  .cache
    Cached?: &#x2705;

%h2 Currently:
.current= render 'panel', forecast: forecast['currently']

%hr
&nbsp;

.hourly
  - collection = forecast.dig('hourly', 'data').first(12)
  - any_precip = collection.any? { |forecast| forecast['precipProbability'].to_f.positive? }
  = render partial: 'panel', collection:, as: :forecast, locals: { small: true, any_precip: }

= javascript_include_tag 'skycons'
= javascript_include_tag 'main'

:javascript
  addSkyConsByClass('skycon');